[project]
name = "allstore"
version = "0.1.0"
description = "Scalable E-Commerce Platform"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.3",
    "fastapi[standard]>=0.128.0",
    "psycopg2-binary>=2.9.11",
    "sqlmodel>=0.0.32",
]
