[project]
name = "allstore"
version = "0.1.0"
description = "Scalable E-Commerce Platform"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "sqlmodel>=0.0.32",
]
